### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by emrekayik** [ekinndev/danisman-akademi-portal#1]
Acaba SQL dosyasını ekleyebilir misiniz? Biraz sorun yaşadımda veri tabanıyla alakalı.

**Comment by ekinndev** [comment]
Emre selam, eski harddiskleri karıştırsam da herhangi bir bir yedek bulamadım malesef bu benim lise yıllarımda yapmış olduğum bir projeydi. Aslında Mysql bağlantısını yaptığında tabloların otomatik oluşması lazım diye hatırlıyorum.
